package com.hxm.mybatis.pojo;

import java.util.Date;

public class Reply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.modifyTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.publishTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Date publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.topicId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.userId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.title
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.content
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.id
     *
     * @return the value of t_reply.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.id
     *
     * @param id the value for t_reply.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.modifyTime
     *
     * @return the value of t_reply.modifyTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.modifyTime
     *
     * @param modifytime the value for t_reply.modifyTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.publishTime
     *
     * @return the value of t_reply.publishTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.publishTime
     *
     * @param publishtime the value for t_reply.publishTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.topicId
     *
     * @return the value of t_reply.topicId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.topicId
     *
     * @param topicid the value for t_reply.topicId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.userId
     *
     * @return the value of t_reply.userId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.userId
     *
     * @param userid the value for t_reply.userId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.title
     *
     * @return the value of t_reply.title
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.title
     *
     * @param title the value for t_reply.title
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.content
     *
     * @return the value of t_reply.content
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.content
     *
     * @param content the value for t_reply.content
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}