package com.hxm.mybatis.pojo;

public class Section {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.name
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.masterId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer masterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.zoneId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer zoneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.logo
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private String logo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.id
     *
     * @return the value of t_section.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.id
     *
     * @param id the value for t_section.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.name
     *
     * @return the value of t_section.name
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.name
     *
     * @param name the value for t_section.name
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.masterId
     *
     * @return the value of t_section.masterId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getMasterid() {
        return masterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.masterId
     *
     * @param masterid the value for t_section.masterId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setMasterid(Integer masterid) {
        this.masterid = masterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.zoneId
     *
     * @return the value of t_section.zoneId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getZoneid() {
        return zoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.zoneId
     *
     * @param zoneid the value for t_section.zoneId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setZoneid(Integer zoneid) {
        this.zoneid = zoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.logo
     *
     * @return the value of t_section.logo
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.logo
     *
     * @param logo the value for t_section.logo
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }
}