package com.hxm.mybatis.pojo;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic.modifyTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic.publishTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Date publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic.title
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic.sectionId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer sectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic.userId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic.good
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer good;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic.top
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic.content
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic.id
     *
     * @return the value of t_topic.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic.id
     *
     * @param id the value for t_topic.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic.modifyTime
     *
     * @return the value of t_topic.modifyTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic.modifyTime
     *
     * @param modifytime the value for t_topic.modifyTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic.publishTime
     *
     * @return the value of t_topic.publishTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic.publishTime
     *
     * @param publishtime the value for t_topic.publishTime
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic.title
     *
     * @return the value of t_topic.title
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic.title
     *
     * @param title the value for t_topic.title
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic.sectionId
     *
     * @return the value of t_topic.sectionId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getSectionid() {
        return sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic.sectionId
     *
     * @param sectionid the value for t_topic.sectionId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setSectionid(Integer sectionid) {
        this.sectionid = sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic.userId
     *
     * @return the value of t_topic.userId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic.userId
     *
     * @param userid the value for t_topic.userId
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic.good
     *
     * @return the value of t_topic.good
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getGood() {
        return good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic.good
     *
     * @param good the value for t_topic.good
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setGood(Integer good) {
        this.good = good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic.top
     *
     * @return the value of t_topic.top
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic.top
     *
     * @param top the value for t_topic.top
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic.content
     *
     * @return the value of t_topic.content
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic.content
     *
     * @param content the value for t_topic.content
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}