package com.hxm.mybatis.pojo;

public class Zone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zone.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zone.name
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zone.description
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zone.id
     *
     * @return the value of t_zone.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zone.id
     *
     * @param id the value for t_zone.id
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zone.name
     *
     * @return the value of t_zone.name
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zone.name
     *
     * @param name the value for t_zone.name
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zone.description
     *
     * @return the value of t_zone.description
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zone.description
     *
     * @param description the value for t_zone.description
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}