package com.hxm.mybatis.mapper;

import com.hxm.mybatis.pojo.Section;
import com.hxm.mybatis.pojo.SectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int countByExample(SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int deleteByExample(SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int insert(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int insertSelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    List<Section> selectByExample(SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    Section selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int updateByExampleSelective(@Param("record") Section record, @Param("example") SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int updateByExample(@Param("record") Section record, @Param("example") SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int updateByPrimaryKeySelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_section
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int updateByPrimaryKey(Section record);
}