package com.hxm.mybatis.mapper;

import com.hxm.mybatis.pojo.Zone;
import com.hxm.mybatis.pojo.ZoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int countByExample(ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int deleteByExample(ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int insert(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int insertSelective(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    List<Zone> selectByExample(ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    Zone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int updateByExampleSelective(@Param("record") Zone record, @Param("example") ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int updateByExample(@Param("record") Zone record, @Param("example") ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int updateByPrimaryKeySelective(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Wed Aug 31 10:16:35 CST 2022
     */
    int updateByPrimaryKey(Zone record);
}